# Generated by Django 3.2 on 2022-05-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_avaliacao_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-id'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-id'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='cursos.curso'),
        ),
    ]
